### ISSUE TITLE
Getting exceptions on New Model

### ISSUE THREAD

**Issue by organPiano2015** [AuthorizeNet/sample-code-java#11]
For responses in New Model in https://github.com/AuthorizeNet/sdk-java/, I tried the sample code on this page and sample code on https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/RecurringBilling/GetListOfSubscriptions.java

I got the same exceptions:
[error] n.a.u.HttpUtility - Execution error for http post Message: 'java.lang.Ar
rayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy'

and the response is always null due to this exception.

same as other types of request/response in New Model of ARB.

Can anybody take  a look?

Thanks.

**Comment by organPiano2015** [comment]
Fixed after updating to the latest source.

**Comment by brianmc** [comment]
Thanks for the update.
