### ISSUE TITLE
Inability to run Visa Checkout sample codes for the SampleCode.java

### ISSUE THREAD

**Issue by Zeeshan7293** [AuthorizeNet/sample-code-java#41]
In the SampleCode.java, while displaying the options for choosing which sample code to run (Code Sample Names), the displayed options are:
       DecryptVisaCheckoutData 
       CreateVisaCheckoutTransaction
 
However, in the switch case the case operands are named differently.
            case "VisaCheckoutDecrypt":
                DecryptVisaCheckoutData.run(apiLoginId, transactionKey);
                break;
            case "VisaCheckoutTransaction":
                CreateVisaCheckoutTransaction.run(apiLoginId, transactionKey);
                break;

This causes both these sample code to never run from the SampleCode.java.

**Comment by brianmc** [comment]
Fixed by https://github.com/AuthorizeNet/sample-code-java/pull/42
