### ISSUE TITLE
Cant run ValidateCustomerPaymentProfile.

### ISSUE THREAD

**Issue by Zeeshan7293** [AuthorizeNet/sample-code-java#43]
In SampleCode.java, in the displayed list of option of sample codes ValidateCustomerPaymentProfile is not there. There is no case expression for it also. Thus one can't run ValidateCustomerPaymentProfile  using the SampleCode.java.

**Comment by brianmc** [comment]
Thanks @Zeeshan7293, if you have a chance please submit a pull request and we'll get this updated.

**Comment by sunnyrajrathod** [comment]
This is fixed and merged in zeeshan's pull request https://github.com/AuthorizeNet/sample-code-java/pull/45.
We can close this issue.
