### ISSUE TITLE
Refund example not complete

### ISSUE THREAD

**Issue by ivanvs** [AuthorizeNet/sample-code-java#44]
Hi, first of all thank you for such a good examples. 

It seems to me that refund example: https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/PaymentTransactions/RefundTransaction.java is not complete.

From example I would say that credit card number is not needed for transaction to be refunded. But when I tried to reuse example I cannot refund money to user.
Error that I got in xml response is: <errorText>Credit card number is required.</errorText>

In ruby example there is credit card number that need to be submitted in order to refund money: https://github.com/AuthorizeNet/sample-code-ruby/blob/master/PaymentTransactions/refund-transaction.rb

Also from example I cannot tell how can I set amount of money that will be refunded.

Could you please tell me if this information is really missing in example or I am doing something wrong?

Thank you!

**Comment by brianmc** [comment]
Hi @ivanvs, thank-you for the feedback you are absolutely correct and this sample was incomplete.  I have updated the sample including adding better print out of error messages returned in the API: 

https://github.com/AuthorizeNet/sample-code-java/commit/b0e58e7d1cfdd7f19cea6366276648268562ffe9

Please accept our thanks for reporting this issue and contributing to our sample code project.

Brian

**Comment by ivanvs** [comment]
Hi @brianmc thank you for your fast response. Refund example is now much better.
