### ISSUE TITLE
TLS Disablement 

### ISSUE THREAD

**Issue by georgantasp** [AuthorizeNet/sample-code-java#64]
I can't seem to get these samples to run in Java 7. The issue seems to be related to TLS Disablement in the sandbox environment and the fact that TLS 1.2 is supported, but not enabled by default in Java 7. This also seems be be the cause of this build failing in Travis.

I have been trying for a solution for a few days without success. Is there an ETA on Authorize.net providing a solution? -Or is Java 7 support going to be discontinued?

**Comment by NexWeb** [comment]
In Java 7 TLS 1.2 is not enabled by default. 
```
 try {
        SSLContext ctx = SSLContext.getInstance("TLSv1.2");
        ctx.init(null, null, null);
        SSLContext.setDefault(ctx);
} catch (Exception e) {
        System.out.println(e.getMessage());
}
```

Or 

```
final SSLContext sc = SSLContext.getInstance("TLSv1.2");
			sc.init(null,null, new java.security.SecureRandom());
			final SSLSocketFactory socketFactory = sc.getSocketFactory();
			HttpsURLConnection.setDefaultSSLSocketFactory(socketFactory);
```

**Comment by gnongsie** [comment]
Thank you for raising this issue. The fix for this has been merged and will be available in the next release for the Java SDK. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.
