### ISSUE TITLE
Result Code: Error E00011 - Access denied. You do not have permissions to call the Transaction Details API.

### ISSUE THREAD

**Issue by dinsahu** [AuthorizeNet/sample-code-java#74]

**Comment by kikmak42** [comment]
Result Code: Error E00011 - Access denied. means the Transaction details API is disabled.

Solution
Step 1. Log in to your account at the Merchant Interface.
Step 2. Enter your login ID and password.
Step 3. Click Account.
Step 4. Under Security Settings, click Transaction Details API.
Step 5. Enter your secret answer.
Step 6. Click Enable Transaction Details API.
